Spprint 9
fixercom/java-filmorate pull request #1
Opened 2022-11-14 06:42 UTC by fixercom

Controllers films users

2022-11-14 20:05 UTC, krylov-sergey-sergeevich requested changes
Привет, отличная работа, но можно лучше, давай доработаем и будет зачет =)

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/annotation/DateAfterBirthdayMovie.java
> +public @interface DateAfterBirthdayMovie {
Красиво, прям хорошо

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Хочу видеть тут аннотацию ломбока чтобы не было конструктора

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
Плюс хочу логи

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
Хочу видеть тут аннотацию ломбока чтобы не было конструктора + логи

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorMessage.java
> +    private int statusCode;
Давай Int?

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Не обязательно: java doc

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
Не обязательно: java doc

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    void updateFilm() {
Рекомендую тест методы называть со слова test те testUpdateFilm

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    void createUser() {
Рекомендую тест методы называть со слова test

2022-11-14 20:05 UTC, krylov-sergey-sergeevich commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    void updateUser() {
Рекомендую тест методы называть со слова test

2022-11-15 12:00 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +public class FilmController {
+

2022-11-15 12:01 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +public class UserController {
\+

2022-11-15 12:05 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorMessage.java
> +    private int statusCode;
Привет Сергей, сделал переменную ссылочным типом. Меня давно мучает этот вопрос что используют в реальной разработке обертки или примитивы тоже применяют или это от чего то зависит?

2022-11-15 12:06 UTC, fixercom commented on src/test/java/ru/yandex/practicum/filmorate/service/FilmServiceTest.java
> +    void updateFilm() {
\+

2022-11-15 12:09 UTC, fixercom commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    void updateUser() {
\+

2022-11-15 12:09 UTC, fixercom commented on src/test/java/ru/yandex/practicum/filmorate/service/UserServiceTest.java
> +    void createUser() {
\+

2022-11-15 12:13 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +public class Film {
Здесь я не понял вопроса:)

2022-11-15 12:14 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +public class User {
И тут тоже никак не соображу что нужно сделать

2022-11-16 05:38 UTC, krylov-sergey-sergeevich approved these changes
Привет, ну все отлично - зачет!

2022-11-16 05:45 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/handler/ErrorMessage.java
> +    private int statusCode;
Стараются почти всегда использовать ссылочный тип, но иногда в нагрузочных местах где создается очень много объектов и их время жизни очень короткое используют примитивы, нет прямого правила, скорее "вроде тут так будет удобнее и правильнее"

2022-11-16 15:47 UTC, merged