Sprint 10 Add friends likes
fixercom/java-filmorate pull request #2
Opened 2022-11-25 09:08 UTC by fixercom

2022-11-26 08:28 UTC, krylov-sergey-sergeevich requested changes
Привет, отличная работа заслуживающая зачет, но оставил пару комментариев будет желание можем по ним что нибудь обсудить. Если нет то присылай обратно и поставлю зачет =)

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Сервер получил PUT запрос '/films/{}/like/{}'", id, userId);
Попробуй поизучать механизмы которые позволят получать путь в контроллере, а не копировать и вставлять его самому

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping(value = "/{id}/like/{userId}")
@ResponseStatus(HttpStatus.NO_CONTENT) - посмотри что это и оцени нужно или нет тут

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Выше был комментарий который говорил "поизучать способы получения путей по которому был запрос" вот сюда тоже рекомендую те знания которые получишь применить

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Чтобы например в тексте ошибки было "по такому пути с таким то данными произошло то то "

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
Это не критично сейчас для зачета - это скорее задача со звездочкой подумать поизучать

2022-11-26 08:28 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
В качестве задания для себя можешь попробовать написать AbstractStorage на дженериках чтобы FilmStorage от него шел и определил в себе дженерик тип как фильм, а в имплементации уже реализация. Далее такой AbstractStorage  ты сможешь и для UserStorage применить. Но это так побаловаться с абстракциями и т.д.

2022-11-27 08:05 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        log.debug("Сервер получил PUT запрос '/films/{}/like/{}'", id, userId);
Привет Сергей! Нашел решение через HttpServletRequest, пришлось добавить его в параметры методов контроллеров

2022-11-27 08:05 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @DeleteMapping(value = "/{id}/like/{userId}")
добавил

2022-11-27 08:06 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +public class GlobalExceptionHandler {
поправил

2022-11-27 08:07 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmStorage.java
> +public interface FilmStorage {
Добавил абстрактный класс, правда не уверен на 100% что сделал все правильно:) Но по крайней мере от части дублирующего кода удалось избавиться

2022-11-27 13:33 UTC, krylov-sergey-sergeevich approved these changes
Привет, отлично поработал - зачет!

2022-11-27 17:00 UTC, merged