feat: добавить базу данных и DAO слой
fixercom/java-filmorate pull request #3
Opened 2022-12-18 10:57 UTC by fixercom

2022-12-19 15:10 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, давай местами доработаем и обсудим некоторые моменты реализации =)

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <version>2.1.214</version>
Версию можно вынести в properties блок, почитай в pom файле в maven

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +
Почему то вся крутая логика в методе handleMethodArgumentNotValidException не применяется в аналогичных местах, есть причина? я про  request.getMethod(), request.getRequestURI()

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +@Transactional
без readonly?

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jdbc</artifactId>
Уточню, разве обязательно spring-boot-starter-data-jdbc, почему не spring-boot-starter-data-jpa?

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException;
Разве нужен этот метод в интерфейсе тут? По сути же это приватный утилитный механизм

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    Genre mapRowToGenre(ResultSet resultSet, int rowNum) throws SQLException;
Разве нужен этот метод в интерфейсе тут? По сути же это приватный утилитный механизм

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDao.java
> +    MPA mapRowToMpa(ResultSet resultSet, int rowNum) throws SQLException;
Разве нужен этот метод в интерфейсе тут? По сути же это приватный утилитный механизм

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    User mapRowToUser(ResultSet resultSet, int rowNum) throws SQLException;
Разве нужен этот метод в интерфейсе тут? По сути же это приватный утилитный механизм

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +@Transactional
readonly надо аль нет? =)

2022-12-19 15:10 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +create table FILMS
not nul - где надо везде добавить
и if not exists для таблиц

2022-12-20 13:07 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/handler/GlobalExceptionHandler.java
> +
Привет Сергей! Попробовал добавить в аналогичные места  и у меня получилось дублирование логов, сразу вспомнил почему я изначально не прописал в других методах. Я так понимаю hibernate validator делает проверку до того как передается запрос в метод контроллера, поэтому логи в контроллере не выводились в консоль когда вылетало исключение. Остальные исключения создавал я, и бросаю их уже внутри метода контроллера, поэтому логи отображаются нормально. На всякий случай более подробно залогировал сервисы, вроде как все в логах все запросы отображаются

2022-12-21 05:03 UTC, fixercom commented on pom.xml
> +            <version>2.1.214</version>
Поправил

2022-12-21 06:11 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/FilmDaoImpl.java
> +@Transactional
Здесь у меня было самое интересное. В первоначальной версии после запуска Postman тестов проходило 20-30 штук и полностью забивало пул потоков HikariPool все повисало. Дня три не мог ничего сделать, везде пишут что утечка памяти и т.д. Потом где то прочитал что надо все методы пометить Transactional и это сработало, не знаю правда почему и что там под капотом происходит:) Сейчас в итоге устранил проблему упростив сложные методы обращения к БД в dao классах, а еще методы которые возвращают стримы из класса JdbcTemplate  заменил на аналогичные без стримов. Возможно я их как то не правильно использовал.

2022-12-21 06:11 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/impl/GenreDaoImpl.java
> +@Transactional
Поправил

2022-12-21 06:47 UTC, fixercom commented on pom.xml
> +            <artifactId>spring-boot-starter-data-jdbc</artifactId>
Заменил, взял из лекции просто spring-boot-starter-data-jdbc, о существовании spring-boot-starter-data-jpa не знал даже:)

2022-12-21 07:19 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    Film mapRowToFilm(ResultSet resultSet, int rowNum) throws SQLException;
Согласен, просто у меня в FilmDaoImpl метод getGenresByFilmId использовал mapRowToGenre из класса  genreDaoImpl, решил таким образом открыть доступ к этому методу из объекта типа genreDao, но тоже сразу были предположения что это не совсем хорошо..... в остальных классах также добавил в интерфейс методы для единообразия. Сейчас все поправил назад. Перенес метод getGenresByFilmId непосредственно в genreDao, не знаю правда это корректно или нет. Таблица то общая для связи фильмов и жанров непонятно к какому dao ее правильнее отнести.

2022-12-21 07:22 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/GenreDao.java
> +    Genre mapRowToGenre(ResultSet resultSet, int rowNum) throws SQLException;
Поправил

2022-12-21 07:22 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/MpaDao.java
> +    MPA mapRowToMpa(ResultSet resultSet, int rowNum) throws SQLException;
Убрал

2022-12-21 07:22 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    User mapRowToUser(ResultSet resultSet, int rowNum) throws SQLException;
Убрал

2022-12-21 07:42 UTC, fixercom commented on src/main/resources/schema.sql
> +create table FILMS
Добавил

2022-12-22 06:54 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки и комментарии - зачет!

2022-12-23 11:26 UTC, merged