Develop
fixercom/java-filmorate pull request #30
Opened 2023-01-20 17:51 UTC by fixercom

2023-01-21 19:07 UTC, krylov-sergey-sergeevich requested changes
Привет, поздравляю это первая командная работа и надеюсь вам понравилось :)

1) Readme в нем никаких правок, что я жду
- название выбранных фич которые вы реализовали и кто что сделал
- у нас добавились сущности и значит можно обновить схему бд

2) Qualifier просьба пройтись по всему проекту и понять точно ли они вам нужны, в обычных проектах эта аннотация практически не используется, поэтому надо проверить все случаи ее использования

3)  Третий момент который +- то есть то нет, рекомендую делать названия методов говорящими и не забываем что названия переменных в методах тоже большое значение имеет

4) Исключения: я вижу что у вас хороший подход и есть такие исключения как LikeDoesNotExist и т.д, НО давайте заметим проблему у нас повторяется логика что перед каждым выбросом исключения мы генерируем message и выходит следующее
throw LikeDoesNotExist("случилось то и то c id потому что это так вышло")

что  я хочу увидеть после исправления
throw LikeDoesNotExist(id) но чтобы в том что увидит человек после исключения ничего не поменялось

5) Второстепенный шаг не обязательно сейчас, все что пишем в логи можно постепенно переводить на англ и в исключениях тоже, пора привыкать

Буду ждать с доработками =)

2023-01-21 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @Qualifier("directorService")
Для чего тут аннотация Qualifier разве есть необходимость?

2023-01-21 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @Qualifier("reviewService")
Разве необходима аннотация?

2023-01-21 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    void delete(long id);
удаление кого? надо или в переменной отразить название или в нейминге метода

2023-01-21 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    void delete(long id);
Удаление чего? Улучшить нейминг или переменной или метода

2023-01-21 19:07 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    List<Film> getSearchByAll(String query);
ByAll что? ByAllField например можно

2023-01-23 03:08 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/DirectorController.java
> +    @Qualifier("directorService")
Убрали

2023-01-23 03:08 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    @Qualifier("reviewService")
Убрали

2023-01-23 03:09 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDao.java
> +    void delete(long id);
Поправили

2023-01-23 03:09 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    void delete(long id);
Поправили

2023-01-23 03:09 UTC, fixercom commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDao.java
> +    List<Film> getSearchByAll(String query);
Поправили

2023-01-24 06:17 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки, все хорошо - зачет!

2023-01-24 06:23 UTC, merged